### ISSUE TITLE
compatibility with variables

### ISSUE THREAD

**Issue by theogrebeude** [bitfocus/companion-module-imagine-lrc#2]
Hi @RossIV  & @JeffreyDavidsz 

firstly, I would like to thank you for the work done to create this plugin. Very useful in a broadcast environment.

I trying to re-create, more or less, a router panel with your tool. 
For the first time, I did all the configuration manually. 
20 pages 14 boutons.
afterwards, I thought it would be practical to be able to change the controlled destination; In my case, all the buttons are linked to the same destination.
After that, I discovered the variable in Companion, a great feature.
So I created a variable name "custom_Router-out", and I created a page to change it with 10 possibilities. 
This part is working well. 
After that, I tried to use the variable in the "Crosspoint Take" action, but I realized the field for the destination it's a list from router input and I'm not able to use my variable here. 
So I tried to use the action "Send a manually-constructed LRC message"
Type: crosspoint control
Operation: Change request
Arguments: ~XPOINT:D${$(internal:custom_Router-out)};S${DX03};U#{0}
With $(internal:custom_Router-out) value of "INGEST03"
It doesn't work. I checked in SDNO the command received was 
"~XPOINT:D${$(internal:custom_Router-out)};S${DX03};U#{0}", so no translation of the variable with it value. 
Just to check I tried to send this command:  ~XPOINT:D${INGEST01};S${DX03};U#{0}
and it's working well. 

I can export to you my configuration if you need it. I'm running companion 2.2.0 (2.2.0-ce7fb5f2-3697) under windows 10. 

I'm not a dev at all, but I would love to help.

I opened your code. and my proposition is, just for testing, to create an action can be named "Crosspoint Take to the variable". With source part like it is and for a destination a free text field : 

```
{
	type: 'textinput',
	label: 'Destination',
	id: 'destination',
	tooltip:
		'Specify a destination by name (e.g. "MON 6") or number (e.g. 1). ' +
		'Multiple destinations may be specified separated by commas (e.g. "MON 6,MON 5,MON 4" or "1,2,3"). ' +
		'WARNING An empty destination resolves to all logical destinations.' +
		'WARNING double check the variable your is correct router destination',
	minChoicesForSearch: 0,
	tags: true,
	multiple: true,
	default: [],
}
```
In place of 

```
{
	type: 'dropdown',
	label: 'Destination',
	id: 'destination',
	tooltip:
		'Specify a destination by name (e.g. "MON 6") or number (e.g. 1). ' +
		'Multiple destinations may be specified separated by commas (e.g. "MON 6,MON 5,MON 4" or "1,2,3"). ' +
		'*WARNING* An empty destination resolves to all logical destinations.',
	minChoicesForSearch: 0,
	tags: true,
	multiple: true,
	regex: '/^[^~\\{},]+$/',
	choices: self.LRC_DESTINATIONS,
	default: [],
}
```

I don't know if that will work. 
I'm not able to test it myself, because I don't know how to compile the plugin and add it to Companion. 

Thanks in advance, 
And congratulations again for the job done. 

Regards, 
Théo

**Comment by RossIV** [comment]
Apologies for the delay - I missed the notifications for this. Your proposal sounds very useful! I'll give that a shot against my router and see if I can get this added for you. Thanks for the suggestion!

**Comment by RossIV** [comment]
After exploring this, I have a counter-proposal that I believe should still meet your needs. I can enable custom inputs in the Destination dropdown and then you could put the variable in there which would avoid a mostly duplicate action.

For example:
![image](https://user-images.githubusercontent.com/1007666/151710328-59f0b0c6-2da6-42fb-a4d4-f2dcafed7626.png)

I also discovered that per https://github.com/bitfocus/companion/issues/1248 I have to manually allow variable parsing, which I'm working on adding everywhere that makes sense and is why that didn't get parsed when you tried manually.

**Comment by RossIV** [comment]
I've implemented my previous proposal in #4. Once that gets merged here then into the latest Companion beta, this should be addressed.

**Comment by RossIV** [comment]
This is in beta as of release a0d8df45 (release May 4th). Should be all set, let me know if you have any issues.

**Comment by RossIV** [comment]
Whoops, I didn't realize I forgot to add variables for feedback. I'll get that added. Thanks for catching that!
