### ISSUE TITLE
Cannot fill "Destination" field

### ISSUE THREAD

**Issue by enricof0** [bitfocus/companion-module-imagine-lrc#5]
Hello

I'm testing this module (companion-module-imagine-lrc) on companion v3.2.2 and I notice a problem.

The module connects correctly to the router (Imagine Platinum MX 15RU) but when I try to add a "Crosspoint Take" action on a key or on a trigger, I cannot fill in the "Destination" field with a number or name (it is ignored) .
With companion 2.4.4 it works correctly, with the same configuration.
The problem occurs even if I don't connect to the router.

Is it a compatibility bug?

Thank you for this useful module!

Enrico

Companion v3.2.2 trigger action whith LRC Crosspoint Take:
![platinum](https://github.com/bitfocus/companion-module-imagine-lrc/assets/166150003/a0f2e7a4-c901-4447-a38d-41d678432bb1)

**Comment by RossIV** [comment]
I've finally had time to update the module to be properly functional in Companion v3. I'll reply back here once it's available in the betas, and that should resolve this issue.

**Comment by RossIV** [comment]
v3 support is complete in #6 which will fix this. I've requested it to be added to the Companion betas, and hopefully will be available shortly.

**Comment by RossIV** [comment]
It's in the betas as of 8/21. Feel free to reach back out with any issues.
